In [1]:
import json
import time
import numpy as np
from stable_baselines3 import PPO

from stable_baselines3.common.vec_env import DummyVecEnv
from itmobotics_gym.envs.single_robot_peginhole_env import SinglePegInHole

pybullet build time: May 31 2023 09:24:34


In [2]:
with open('single_robot_peginhole_gui.json', encoding='UTF-8') as json_file:
    env_config = json.load(json_file)

env = DummyVecEnv([lambda: SinglePegInHole(env_config)])

argv[0]=
startThreads creating 1 threads.
starting thread 0
started thread 0 
argc=3
argv[0] = --unused
argv[1] = 
argv[2] = --start_demo_name=Physics Server
ExampleBrowserThreadFunc started
X11 functions dynamically loaded using dlopen/dlsym OK!
X11 functions dynamically loaded using dlopen/dlsym OK!
Creating context
Created GL 3.3 context
Direct GLX rendering context obtained
Making context current
GL_VENDOR=NVIDIA Corporation
GL_RENDERER=NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
GL_VERSION=3.3.0 NVIDIA 520.61.05
GL_SHADING_LANGUAGE_VERSION=3.30 NVIDIA via Cg compiler
pthread_getconcurrency()=0
Version = 3.3.0 NVIDIA 520.61.05
Vendor = NVIDIA Corporation
Renderer = NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
b3Printf: Selected demo: Physics Server
startThreads creating 1 threads.
starting thread 0
started thread 0 
MotionThreadFunc thread started
ven = NVIDIA Corporation
ven = NVIDIA Corporation
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: No iner

In [3]:
env.action_space

Box([-1. -1. -1. -1. -1. -1.], [1. 1. 1. 1. 1. 1.], (6,), float32)

In [4]:
env.observation_space

Dict(camera:Box([[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]], [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 

In [5]:
env.seed = int(time.time())
obs = env.reset()

b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frame
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: base
Replace object with name table
b3Printf: b3Warning[examples/SharedMemory/PhysicsClientSharedMemory.cpp,1324]:

b3Printf: Removing body failed
Replace object with name hole


In [5]:
action = np.array([[0.0, -1.0, 0.0, 
                   1.0, 1.0, 0.0]])

In [7]:
action = np.array([[0.0, 0.0, -1.0, 
                   0.0, 0.0, 1.0]])

In [8]:
rewards = []
observs = []
for _ in range(10):
    obs, reward, done, info = env.step(action)
    rewards.append(reward[0])
    observs.append(obs['cart_tf'][0])

print(rewards)
print(observs)

[-15.684779, -16.45529, -17.2696, -18.121767, -19.00661, -19.919672, -20.85711, -21.815619, -22.792368, -23.784912]
[array([ 0.28285646,  0.39154384,  0.8364963 ,  2.8358984 , -0.01625785,
        0.30090755], dtype=float32), array([ 0.28250045,  0.39130953,  0.85659534,  2.8358989 , -0.01626305,
        0.3009063 ], dtype=float32), array([ 0.28213996,  0.3910723 ,  0.87669915,  2.8358996 , -0.01626779,
        0.300905  ], dtype=float32), array([ 0.28177494,  0.39083222,  0.8968055 ,  2.8359003 , -0.01626873,
        0.30090535], dtype=float32), array([ 0.28140518,  0.39058894,  0.91691214,  2.8359005 , -0.01627024,
        0.30090466], dtype=float32), array([ 0.28103074,  0.39034256,  0.9370165 ,  2.8359008 , -0.01627198,
        0.30090383], dtype=float32), array([ 0.2806516 ,  0.3900931 ,  0.95711625,  2.835901  , -0.01627396,
        0.3009026 ], dtype=float32), array([ 0.2802675 ,  0.3898404 ,  0.977209  ,  2.8359013 , -0.01627623,
        0.30090094], dtype=float32), array([ 0.2

In [22]:
obs, reward, done, info = env.step(action)
reward

array([-5.9686136], dtype=float32)

In [ ]:
env.close()

In [1]:
import json
import time
from tqdm import tqdm
import cv2


import numpy as np
from itmobotics_gym.envs.single_robot_pybullet_env import SingleRobotPyBulletEnv


with open('single_robot_env.json', encoding='UTF-8') as json_file:
    env_config = json.load(json_file)

env = SingleRobotPyBulletEnv(env_config)
env.seed = int(time.time())
time.sleep(1.0)
env.reset()
time.sleep(1.0)

random_action = np.random.uniform(-1, 1, size=6)
print(random_action.shape)
for i in tqdm(range(1000)):
    obs = env.observation_state_as_dict()
    obs_img = obs['camera']
    
    random_action = np.random.uniform(-1, 1, size=6)

    env._sim.sim_step()
    env._take_action_vector(random_action)
    cv2.imshow('out', obs_img)
    # cv2.imshow('out', env.render())
    cv2.waitKey(1)
    env.step(random_action)


pybullet build time: May 31 2023 09:24:34


argv[0]=
startThreads creating 1 threads.
starting thread 0
started thread 0 
argc=3
argv[0] = --unused
argv[1] = 
argv[2] = --start_demo_name=Physics Server
ExampleBrowserThreadFunc started
X11 functions dynamically loaded using dlopen/dlsym OK!
X11 functions dynamically loaded using dlopen/dlsym OK!
Creating context
Created GL 3.3 context
Direct GLX rendering context obtained
Making context current
GL_VENDOR=NVIDIA Corporation
GL_RENDERER=NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
GL_VERSION=3.3.0 NVIDIA 520.61.05
GL_SHADING_LANGUAGE_VERSION=3.30 NVIDIA via Cg compiler
pthread_getconcurrency()=0
Version = 3.3.0 NVIDIA 520.61.05
Vendor = NVIDIA Corporation
Renderer = NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
b3Printf: Selected demo: Physics Server
startThreads creating 1 threads.
starting thread 0
started thread 0 
MotionThreadFunc thread started
ven = NVIDIA Corporation
ven = NVIDIA Corporation
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: No iner

  8%|▊         | 75/1000 [00:18<03:50,  4.02it/s]


KeyboardInterrupt: 